-- ==================================================
-- SUPABASE PROJECTS SEED DATA DRAFT (002)
-- ==================================================
-- NOTE: Local draft seed file. DO NOT execute remotely without approval.

INSERT INTO public.projects (
  title,
  slug,
  category,
  short_description,
  full_description,
  role,
  period,
  technologies,
  copyright_number,
  demo_url,
  github_url,
  documentation_url,
  is_featured,
  is_published,
  display_order
)
VALUES
(
  'eBro — Smart Poultry Farm Climate Control & Monitoring System',
  'ebro-smart-poultry-farm',
  'IoT & Smart Systems',
  'A copyright-registered LoRa and IoT-based climate control and monitoring system for closed-house broiler poultry farms, combining environmental sensing, HMI, and web-based monitoring.',
  'A copyright-registered LoRa and IoT-based climate control and monitoring system for closed-house broiler poultry farms, combining environmental sensing, HMI, and web-based monitoring.',
  'IoT Engineer & Full-Stack Developer',
  '2025 – 2026',
  ARRAY['LoRa', 'IoT', 'HMI', 'Web Monitoring', 'Embedded Systems'],
  'EC002026157949',
  NULL,
  NULL,
  NULL,
  true,
  true,
  1
),
(
  'End-to-End Solar Panel System for Greenhouse Electrification',
  'greenhouse-solar-panel-system',
  'IoT & Smart Systems',
  'An automation and renewable energy project focused on end-to-end solar panel system implementation for greenhouse electrification.',
  'An automation and renewable energy project focused on end-to-end solar panel system implementation for greenhouse electrification.',
  'Developer',
  '2026',
  ARRAY['Solar Power', 'Electrification', 'Greenhouse'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  2
),
(
  'Automated Greenhouse Monitoring & Control System',
  'automated-greenhouse-monitoring',
  'IoT & Smart Systems',
  'An IoT project for automated environmental monitoring and microclimate control in greenhouse operations.',
  'An IoT project for automated environmental monitoring and microclimate control in greenhouse operations.',
  'Developer',
  '2026',
  ARRAY['IoT', 'Greenhouse', 'Control'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  3
),
(
  'Full-Stack Smart-Eco Tourism Web Platform',
  'smart-eco-tourism-platform',
  'Web & Mobile',
  'A full-stack web platform developed for smart-eco tourism management, information distribution, and interactive visitor services.',
  'A full-stack web platform developed for smart-eco tourism management, information distribution, and interactive visitor services.',
  'Developer',
  '2026',
  ARRAY['Full-Stack', 'Web Dev', 'Tourism'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  4
),
(
  'Smartphone-Based Telemetry & Navigation for Search & Rescue Robots',
  'sar-robot-telemetry-navigation',
  'Robotics & Telemetry',
  'A robotics engineering project focused on smartphone-based telemetry, sensor data streaming, and remote navigation systems for search and rescue platforms.',
  'A robotics engineering project focused on smartphone-based telemetry, sensor data streaming, and remote navigation systems for search and rescue platforms.',
  'Developer',
  '2026',
  ARRAY['Robotics', 'Telemetry', 'Navigation'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  5
),
(
  'Autonomous Surface Vehicle — Undip Robotics Team',
  'autonomous-surface-vehicle-undip',
  'Robotics & Telemetry',
  'An autonomous surface vessel developed for the Indonesian Boat Contest (Kontes Kapal Indonesia), focusing on electrical power management, component analysis, and PCB design.',
  'An autonomous surface vessel developed for the Indonesian Boat Contest (Kontes Kapal Indonesia), focusing on electrical power management, component analysis, and PCB design.',
  'Electrical Staff',
  '2025',
  ARRAY['Robotics', 'ASV', 'Electrical'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  6
),
(
  'Water Tank Control and Monitoring System',
  'water-tank-control-monitoring',
  'Automation & Control',
  'An automation project focused on real-time water level sensing, automated control, and operational status monitoring.',
  'An automation project focused on real-time water level sensing, automated control, and operational status monitoring.',
  'Electrical',
  '2025',
  ARRAY['Automation', 'Control', 'Monitoring'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  7
),
(
  'IoT Practicum Module Production',
  'iot-practicum-module-production',
  'IoT & Smart Systems',
  'Educational hardware and curriculum module production for hands-on IoT practicum and embedded systems laboratory training.',
  'Educational hardware and curriculum module production for hands-on IoT practicum and embedded systems laboratory training.',
  'Module Creator / Developer',
  '2025',
  ARRAY['IoT', 'Embedded', 'Education'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  8
),
(
  'Line Follower Robot Project',
  'line-follower-robot-project',
  'Robotics & Telemetry',
  'An autonomous mobile robotics project focused on high-speed line tracking sensor algorithms and motor control hardware.',
  'An autonomous mobile robotics project focused on high-speed line tracking sensor algorithms and motor control hardware.',
  'Developer',
  '2026',
  ARRAY['Robotics', 'Control', 'Autonomous'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  9
),
(
  'Automatic Time Scheduling Generator',
  'automatic-time-scheduling-generator',
  'Software & Automation',
  'A software application for automatic time scheduling generation, registered under official copyright (HKI).',
  'A software application for automatic time scheduling generation, registered under official copyright (HKI).',
  'Developer',
  '2024',
  ARRAY['Software', 'Automation', 'Copyright'],
  '000621177',
  NULL,
  NULL,
  NULL,
  false,
  true,
  10
),
(
  'Line Follower Robot Competition',
  'line-follower-robot-competition-judge',
  'Robotics & Telemetry',
  'Technical evaluation and officiating role for autonomous line follower robotics competitions.',
  'Technical evaluation and officiating role for autonomous line follower robotics competitions.',
  'Competition Judge',
  '2026',
  ARRAY['Robotics', 'Competition', 'Judging'],
  NULL,
  NULL,
  NULL,
  NULL,
  false,
  true,
  11
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  role = EXCLUDED.role,
  period = EXCLUDED.period,
  technologies = EXCLUDED.technologies,
  copyright_number = EXCLUDED.copyright_number,
  demo_url = EXCLUDED.demo_url,
  github_url = EXCLUDED.github_url,
  documentation_url = EXCLUDED.documentation_url,
  is_featured = EXCLUDED.is_featured,
  is_published = EXCLUDED.is_published,
  display_order = EXCLUDED.display_order,
  updated_at = now();
